version: '3.9'
services:
    
  web01:
    build:
      context: ./web01
    image: web01
    container_name: web01
    restart: always
    tty: true
    networks:
      - rn-network

  web02:
    build:
      context: ./web02
    image: web02
    container_name: web02
    restart: always
    tty: true
    networks:
      - rn-network

  web03:
    build:
      context: ./web03
    image: web03
    container_name: web03
    restart: always
    tty: true
    networks:
      - rn-network
    
  proxy:
    build:
      context: ./proxy
    image: proxy
    container_name: proxy
    restart: always
    tty: true
    ports:
      - "80:80"
    depends_on:
      - web01
      - web02
      - web03
    networks:
      - rn-network
    
  dns:
    build: ./dns
    image: dns
    container_name: ns1
    restart: always
    tty: true
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./dns/primary:/etc/bind
    networks:
      - rn-network
      
networks:
  rn-network:
    driver: bridge